configmap:
  checksum: c129371bc17d66e5
  data:
    config.yaml: "server:\n  port: 8080\nspring:\n  application:\n    name: ad-gateway\n\
      \  cloud:\n    nacos:\n      discovery:\n        server-addr: ${NACOS_SERVERS}\n"
  enabled: true
  mountPath: /config
env:
- name: NACOS_USERNAME
  valueFrom:
    secretKeyRef:
      key: NACOS_USERNAME
      name: nacos-secret
- name: NACOS_PASSWORD
  valueFrom:
    secretKeyRef:
      key: NACOS_PASSWORD
      name: nacos-secret
- name: SPRING_PROFILE
  valueFrom:
    secretKeyRef:
      key: SPRING_PROFILE
      name: nacos-secret
environment: prod
image:
  name: sinozo-test/ad-gateway
  pullSecret: regcred
  pullSecretData: eyJhdXRocyI6eyJzd3IuYXAtc291dGhlYXN0LTMubXlodWF3ZWljbG91ZC5jb20iOnsidXNlcm5hbWUiOiJhcC1zb3V0aGVhc3QtM0BGRkFLV1lJMEpORzlJTkRSVFhHWiIsInBhc3N3b3JkIjoiNzAxNTc1YzczYTQyZTIyY2NkOWFiOWNhNThmMTNiNGUwMWMxMGE0Yzg5ZjhmOTExOThmYzkyMjg3Nzk5ZTk0YyIsImF1dGgiOiJZWEF0YzI5MWRHaGxZWE4wTFROQVJrWkJTMWRaU1RCS1RrYzVTVTVFVWxSWVIxbzZOekF4TlRjMVl6Y3pZVFF5WlRJeVkyTmtPV0ZpT1dOaE5UaG1NVE5pTkdVd01XTXhNR0UwWXpnNVpqaG1PVEV4T1RobVl6a3lNamczTnprNVpUazBZdz09In19fQ==
  registry: swr.ap-southeast-3.myhuaweicloud.com
  tag: Re9a967d17
java:
  enabled: true
  opts: -XX:+UseContainerSupport -XX:MaxRAMPercentage=72.0 -XX:MaxMetaspaceSize=256m
    -XX:InitialRAMPercentage=30.0 -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/tmp/heapdump.hprof -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom
    -Dfile.encoding=UTF-8 -DNACOS_SERVERS=nacos-clusterip.nacos.svc.cluster.local:8848
    -DNACOS_NAMESPACE=adv_test -DNACOS_GROUP=DEFAULT_GROUP -DNACOS_USERNAME=$(NACOS_USERNAME)
    -DNACOS_PASSWORD=$(NACOS_PASSWORD) -Dspring.profiles.active=$(SPRING_PROFILE)
monitoring:
  enabled: true
  path: /actuator/prometheus
  port: 8080
probes:
  enabled: true
  path: /actuator/health
  port: 8080
project: adv
pvc:
  accessModes:
  - ReadWriteOnce
  enabled: true
  storage: 10Gi
  storageClass: alibabacloud-cnfs-nas
resources:
  enabled: true
  limits:
    cpu: '2'
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi
service:
  name: ad-gateway
  namespace: adv-prod
  port: 8080
  replicas: 2
  type: ClusterIP
