apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-puller
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          env:
            - name: JAVA_OPTS
              value: >-
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=70.0
                -XX:+UseG1GC
                -Dfile.encoding=UTF-8
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
