apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-gateway
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          env:
            - name: JAVA_OPTS
              value: >-
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=72.0
                -XX:MaxMetaspaceSize=256m
                -XX:InitialRAMPercentage=30.0
                -XX:MaxGCPauseMillis=200
                -XX:+HeapDumpOnOutOfMemoryError
                -XX:HeapDumpPath=/tmp/heapdump.hprof
                -XX:+UseG1GC
                -Djava.security.egd=file:/dev/./urandom
                -Dfile.encoding=UTF-8
                -DNACOS_SERVERS=nacos-clusterip.nacos.svc.cluster.local:8848
                -DNACOS_NAMESPACE=adv_prod
                -DNACOS_GROUP=DEFAULT_GROUP
                -Dspring.profiles.active=prod
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 800m
              memory: 2Gi
