{{- if .Values.image.createPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  annotations:
    {{- include "generic.annotations" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.pullSecretData }}
{{- end }}
